theme: jekyll-theme-cayman

title: Welcome to Sayed Jobaer's Homepage!
description: |
  Ph.D. in Information and Communication Intelligent Systems
  Donghua University (211, Double First-Class) Â· Shanghai, China


