theme: jekyll-theme-cayman

title: Welcome to Sayed Jobaer's Homepage!
description: >
  Ph.D. in Information and Communication Intelligent Systems<br>
  Donghua University (211, Double First-Class), Shanghai, China<br><br>

  <a href="mailto:sayedjobaer@hotmail.com" title="Email">
    <img src="/assets/email.svg" style="vertical-align:middle;">
  </a>
  &nbsp;
  <a href="https://github.com/Sayed-Jobaer" target="_blank" title="GitHub">
    <img src="/assets/github.svg" style="vertical-align:middle;">
  </a>
  &nbsp;
  <a href="/assets/cv.pdf" target="_blank" title="CV">
    <img src="/assets/pdf.svg" style="vertical-align:middle;">
  </a>
  &nbsp;
  <a href="https://scholar.google.com/citations?user=fCM8lL8AAAAJ&hl=en" target="_blank" title="Google Scholar">
    ðŸŽ“
  </a> 



