theme: jekyll-theme-cayman
css: /assets/style.css


title: Welcome to Sayed Jobaer's Homepage!
description: "Ph.D. in Information and Communication Intelligent Systems<br>Donghua University (211, Double First-Class), Shanghai, China"



